name: arena
version: 1.0.0 
description: >-
  Have you been turned into a newt?  Would you like to be?
  This package can help. It has all of the
  newt-transmogrification functionality you have been looking
  for.
author: jamapps
homepage: www.google.com
documentation: www.google.com
dependencies:
  process: "^3.0.1"
